### ISSUE TITLE
Bluetooth LE Link Layer Relay Attacks

### ISSUE THREAD

**Issue by chibataiki** [delikely/Automotive-Security-Timeline#4]
按时间搜索了下应该没收录
https://hardwear.io/netherlands-2022/speakers/sultan-khan.php
https://hardwear.io/netherlands-2022/presentation/bluetooth-LE-link-layer-relay-attacks.pdf
https://www.youtube.com/watch?v=2CvHM5gZVnY

**Comment by delikely** [comment]
感谢！ BLE中继已经收录，收录的是NCC对Tesla的中继案例。但仍将会添加这个演讲作为补充材料。
![image](https://github.com/delikely/Automotive-Security-Timeline/assets/11872405/3b9a1432-3ed3-4ff7-a280-8729e22b3b3f)
